"""Adiciona campo de imagem aos modelos

Revision ID: e665aa1dae7e
Revises: 
Create Date: 2025-06-12 23:30:15.511891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e665aa1dae7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_file', sa.String(length=100), nullable=False, server_default='default.jpg'))

    with op.batch_alter_table('ponto_turistico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_file', sa.String(length=100), nullable=False, server_default='default.jpg'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ponto_turistico', schema=None) as batch_op:
        batch_op.drop_column('imagem_file')

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('imagem_file')

    # ### end Alembic commands ###
